import { Inter } from "next/font/google";
import ThemeRegistry from './ThemeRegistry'; // Import the client-side theme provider component

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeRegistry> {/* Wrap the children with ThemeRegistry to apply the theme */}
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
